
# @uri = https://func-aifsrd-response-generator-nxt.azurewebsites.net/api
@uri = http://localhost:7071/api
@messageId = item1


###

POST {{uri}}/MessageFromBody
content-type: application/json

{
    "id": "item1",
    "sentiment": "positive"
}

###

POST {{uri}}/MessageFromBinding/{{messageId}}
content-type: application/json

###

POST {{uri}}/ManualDeserialization
content-type: application/json

{
    "id": "item1",
    "sentiment": "positive"
}


###

POST https://func-aifsrd-conversational-ai-nxt.azurewebsites.net/api/createResponse/{messageId}/{respondAs}?code=p4or4KcH1scrhFmAa_TYzNJ4BLFe62elsckGwvE2rG5qAzFudQ0v9Q%3D%3D
content-type: application/json

