
# @uri = https://func-aifsrd-response-generator-nxt.azurewebsites.net/api
@uri = http://localhost:7071/api
@messageId = item1


###

POST {{uri}}/MessageFromBody/item1
content-type: application/json

{
    "id": "item1",
    "sentiments": ["positive","neutral"]
}

###

POST {{uri}}/MessageFromBinding/item1
content-type: application/json

###

POST {{uri}}/ManualDeserialization
content-type: application/json

{
    "id": "item1",
    "sentiments": ["positive","neutral"]
}